DELETE http://localhost:3003/api/blogs/64d9e90b210fb21e098ef3ee
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJlaG51bWEiLCJpZCI6IjY0ZDljZWVkMDZlMzFjYWVhMGE2ODNjOSIsImlhdCI6MTY5MjAwMjUwMSwiZXhwIjoxNjkyMDA2MTAxfQ.gdyDNdnNyPOn82nHQZXYKiv1cNuz0TjtlkUXPA2kq58